/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateReturnOrderArgs } from "./CreateReturnOrderArgs";
import { UpdateReturnOrderArgs } from "./UpdateReturnOrderArgs";
import { DeleteReturnOrderArgs } from "./DeleteReturnOrderArgs";
import { ReturnOrderFindManyArgs } from "./ReturnOrderFindManyArgs";
import { ReturnOrderFindUniqueArgs } from "./ReturnOrderFindUniqueArgs";
import { ReturnOrder } from "./ReturnOrder";
import { ReturnOrderService } from "../returnOrder.service";

@graphql.Resolver(() => ReturnOrder)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ReturnOrderResolverBase {
  constructor(
    protected readonly service: ReturnOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ReturnOrder",
    action: "read",
    possession: "any",
  })
  async _returnOrdersMeta(
    @graphql.Args() args: ReturnOrderFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ReturnOrder])
  @nestAccessControl.UseRoles({
    resource: "ReturnOrder",
    action: "read",
    possession: "any",
  })
  async returnOrders(
    @graphql.Args() args: ReturnOrderFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReturnOrder[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ReturnOrder",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ReturnOrder, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReturnOrder",
    action: "read",
    possession: "own",
  })
  async returnOrder(
    @graphql.Args() args: ReturnOrderFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReturnOrder | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ReturnOrder",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ReturnOrder)
  @nestAccessControl.UseRoles({
    resource: "ReturnOrder",
    action: "create",
    possession: "any",
  })
  async createReturnOrder(
    @graphql.Args() args: CreateReturnOrderArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReturnOrder> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ReturnOrder",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ReturnOrder"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ReturnOrder)
  @nestAccessControl.UseRoles({
    resource: "ReturnOrder",
    action: "update",
    possession: "any",
  })
  async updateReturnOrder(
    @graphql.Args() args: UpdateReturnOrderArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ReturnOrder | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ReturnOrder",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ReturnOrder"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ReturnOrder)
  @nestAccessControl.UseRoles({
    resource: "ReturnOrder",
    action: "delete",
    possession: "any",
  })
  async deleteReturnOrder(
    @graphql.Args() args: DeleteReturnOrderArgs
  ): Promise<ReturnOrder | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
